blueprints/product/views.py
import datetime as dt
from app import app
from flask import Blueprint, send_from_directory, session, url_for, redirect
from blueprints.product.models import Product, ProductImage
from blueprints.cart.models import Cart, CartItem


product_bp = Blueprint('product', __name__, url_prefix='/products')
Product.create_table()
ProductImage.create_table()


@product_bp.route('/uploads/<string:filename>')
def product_image(filename):
    return send_from_directory(app.config['UPLOAD_FOLDER'], filename)


@product_bp.route('/<int:product_id>/add-to-cart')
def add_to_cart(product_id):
    user_id = session.get('user_id')
    product = Product.get_by_id(product_id)
    cart = Cart.get_active_cart(user_id)

    cart_items = CartItem.filter(cart=cart, product=product)
    if not cart_items:
        CartItem.create(
            cart=cart,
            product=product
        )
    else:
        cart_item = cart_items[0]
        cart_item.amount += 1
        cart_item.updated_at = dt.datetime.now()
        cart_item.save()

    return redirect(url_for('home'))

blueprints/user/views.py
from flask import Blueprint, render_template
from blueprints.cart.models import Cart, CartItem, Order
from blueprints.cart.forms import CartItemEditForm


user_bp = Blueprint('user', __name__, url_prefix='/users')


@user_bp.route('/<int:user_id>/cart', methods=['GET', 'POST'])
def cart(user_id):
    form = CartItemEditForm()
    _cart = Cart.get_active_cart(user_id)
    cart_items = CartItem.filter(cart=_cart)
    return render_template('users/cart.html', cart=_cart, cart_items=cart_items, form=form)


@user_bp.route('/<int:user_id>/orders')
def orders(user_id):
    carts = Cart.filter(user_id=user_id, active=False)
    _orders = []
    for _cart in carts:
        order = Order.get(Order.cart == _cart)
        _orders.append(order)
    return render_template('users/orders.html', orders=_orders)


@user_bp.route('/<int:user_id>/orders/<int:order_id>')
def order_details(user_id, order_id):
    order = Order.get_by_id(order_id)
    cart_items = CartItem.filter(cart=order.cart)
    return render_template('users/order_details.html', order=order, cart_items=cart_items)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">

  <title>RIMI Shop</title>

  <!-- Bootstrap core CSS -->
  <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>

<body>
  <!-- Navigation -->
  {% include "navigation.html" %}

  <!-- Page Content -->
  <div class="container">
    <div class="row">

      <!-- Alerts -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <div class="col-6 mt-4 mx-auto">

          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            {{ message }}
          </div>
          {% endfor %}

        </div>
      {% endif %}
      {% endwith %}

      <!-- Form Errors -->
      {% if form and form.errors %}
        <div class="col-6 mt-4 mx-auto">
          <div class="alert alert-danger">
            {% for field, errors in form.errors.items() %}
              <p>{{ form[field].label }}: {{ ', '.join(errors) }}</p>
            {% endfor %}
          </div>
        </div>
      {% endif %}

      <!-- Content -->
      {% block content %}
      {% endblock %}

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- JS -->
  <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

</body>
</html>

templates/footer.html
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; RIMI Shop 2020</p>
  </div>
  <!-- /.container -->
</footer>

templates/home.html
{% extends "base.html" %}

{% block content %}
  <!-- Products -->
  <div class="col-lg-12">
    <div class="row mt-4">

      <!-- Product -->
      {% for product in products %}
      <div class="col-lg-3 col-md-6 col-sm-12 mb-4">
        <div class="card h-100">

          {% if product.images %}
            <img class="card-img-top" style="max-height: 400px" src="{{ url_for('product.product_image', filename=product.images.0.image) }}" alt="">
          {% else %}
            <img class="card-img-top" src="http://placehold.it/700x400" alt="">
          {% endif %}

          <div class="card-body">
            <h4 class="card-title">
              {{ product.name }}
            </h4>
            <h5>
              {{ product.price }} EUR
            </h5>
            <p class="card-text">
              {{ product.description|truncate }}
            </p>
          </div>

          <!-- Add to Cart Button -->
          {% if session.is_authenticated %}
          <div class="card-footer">
            <a class="btn btn-sm btn-outline-primary" href="{{ url_for('product.add_to_cart', product_id=product.id) }}">
              Add To Cart
            </a>
          </div>
          {% endif %}

        </div>
      </div>
      {% endfor %}

    </div>
    <!-- /.row -->

  </div>
  <!-- /.col-lg-9 -->
{% endblock %}

templates/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">RIMI Shop</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">

        <!-- Home -->
        <li class="nav-item active">
          <a class="nav-link" href="/">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if not session.is_authenticated %}
        <!-- Register -->
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
        </li>

        <!-- Login -->
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
        </li>
        {% endif %}

        {% if session.is_authenticated %}
        <!-- User -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">User</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('user.cart', user_id=session.user_id) }}">My Cart</a>
            <a class="dropdown-item" href="{{ url_for('user.orders', user_id=session.user_id) }}">My Orders</a>

            <!-- Admin -->
            {% if session.is_admin %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('admin.users_overview') }}">Edit Users</a>
            <a class="dropdown-item" href="{{ url_for('admin.products_overview') }}">Edit Products</a>
            <a class="dropdown-item" href="#">Edit Orders</a>
            {% endif %}

            <!-- Logout -->
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a>
          </div>
        </li>
        {% endif %}

      </ul>
    </div>

  </div>
</nav>