blueprints/cart/models.py
import datetime as dt
from peewee import *
from app import db
from blueprints.auth.models import User
from blueprints.product.models import Product


class Cart(Model):
    user = ForeignKeyField(User, null=False, related_name='carts')
    active = BooleanField(null=False, default=True)
    created_at = DateTimeField(default=dt.datetime.now)
    updated_at = DateTimeField(null=True)

    class Meta:
        database = db

    @classmethod
    def get_active_cart(cls, user_id):
        # cart = Cart.select().where(Cart.user_id == user_id, Cart.active == True)
        carts = Cart.filter(user_id=user_id, active=True)
        if not carts:
            cart = Cart.create(user_id=user_id)
        else:
            cart = carts[0]
        return cart

    def get_total_price(self):
        total_price = 0
        cart_items = CartItem.filter(cart=self)
        for item in cart_items:
            total_price += item.get_total_price()
        return total_price


class CartItem(Model):
    cart = ForeignKeyField(Cart, null=False)
    product = ForeignKeyField(Product, null=False)
    amount = IntegerField(null=False, default=1)
    created_at = DateTimeField(default=dt.datetime.now)
    updated_at = DateTimeField(null=True)

    class Meta:
        database = db

    def get_total_price(self):
        return self.product.price * self.amount


class Order(Model):
    cart = ForeignKeyField(Cart, null=False, related_name='orders')
    total = IntegerField(null=False, default=0)
    address = CharField(null=False)
    created_at = DateTimeField(default=dt.datetime.now)
    updated_at = DateTimeField(null=True)

    class Meta:
        database = db

blueprints/cart/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import IntegerField
from wtforms.validators import DataRequired, NumberRange


class CartItemEditForm(FlaskForm):
    amount = IntegerField('amount', validators=[DataRequired(), NumberRange(min=1)])

blueprints/cart/views.py
from flask import Blueprint, redirect, url_for, session, flash
from blueprints.cart.models import Cart, CartItem, Order
from blueprints.cart.forms import CartItemEditForm


cart_bp = Blueprint('cart', __name__, url_prefix='/carts')
Cart.create_table()
CartItem.create_table()
Order.create_table()


# edit item amount in user cart
# delete items from user cart


@cart_bp.route('/<int:cart_id>/finish')
def finish(cart_id):
    cart = Cart.get_by_id(cart_id)
    cart.active = False
    cart.save()

    Order.create(
        cart=cart,
        total=cart.get_total_price(),
        address='',
    )

    return redirect(url_for('home'))


@cart_bp.route('/<int:cart_id>/item/<int:item_id>/edit', methods=['POST'])
def edit_item(cart_id, item_id):
    user_id = session.get('user_id')
    item = CartItem.get(id=item_id, cart_id=cart_id)

    form = CartItemEditForm()
    if form.validate_on_submit():
        amount = form.amount.data
        item.amount = amount
        item.save()
        flash(f'Product {item.product.name} was updated', 'success')
        return redirect(url_for('user.cart', user_id=user_id))

    flash(f'Product {item.product.name} was not updated', 'danger')
    return redirect(url_for('user.cart', user_id=user_id))


@cart_bp.route('/<int:cart_id>/item/<int:item_id>/delete')
def delete_item(cart_id, item_id):
    user_id = session.get('user_id')
    item = CartItem.get(id=item_id, cart_id=cart_id)
    item.delete_instance()
    flash(f'Product {item.product.name} was deleted successfully', 'success')
    return redirect(url_for('user.cart', user_id=user_id))

blueprints/user/views.py
from flask import Blueprint, render_template
from blueprints.cart.models import Cart, CartItem, Order
from blueprints.cart.forms import CartItemEditForm


user_bp = Blueprint('user', __name__, url_prefix='/users')


@user_bp.route('/<int:user_id>/cart', methods=['GET', 'POST'])
def cart(user_id):
    form = CartItemEditForm()
    _cart = Cart.get_active_cart(user_id)
    cart_items = CartItem.filter(cart=_cart)
    return render_template('users/cart.html', cart=_cart, cart_items=cart_items, form=form)


@user_bp.route('/<int:user_id>/orders')
def orders(user_id):
    carts = Cart.filter(user_id=user_id, active=False)
    _orders = []
    for _cart in carts:
        order = Order.get(Order.cart == _cart)
        _orders.append(order)
    return render_template('users/orders.html', orders=_orders)


@user_bp.route('/<int:user_id>/orders/<int:order_id>')
def order_details(user_id, order_id):
    order = Order.get_by_id(order_id)
    cart_items = CartItem.filter(cart=order.cart)
    return render_template('users/order_details.html', order=order, cart_items=cart_items)

templates/users/cart.html
{% extends "base.html" %}

{% block content %}
  <div class="container my-4">
    <div class="row">
      <div class="col-4">
        <h1>Cart</h1>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-12">
        <table class="table table-striped">
          <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Amount</th>
            <th scope="col">Total Price</th>
            <th scope="col"></th>
          </tr>
          </thead>
          <tbody>
          {% for item in cart_items %}
            <form action="{{ url_for('cart.edit_item', cart_id=cart.id, item_id=item.id) }}" method="post">
              {{ form.csrf_token() }}

              <tr>
                <th scope="row">{{ item.id }}</th>
                <td>{{ item.product.name }}</td>
                <td>{{ item.product.price }}</td>
                <td>
                  <input type="number" name="amount" min="1" value="{{ item.amount }}">
                </td>
                <td>{{ item.get_total_price() }}</td>
                <td>
                  <button type="submit" class="btn btn-primary">Save</button>
                  <a href="{{ url_for('cart.delete_item', cart_id=cart.id, item_id=item.id) }}" type="button" class="btn btn-danger">Delete</a>
                </td>
              </tr>

            </form>
          {% endfor %}
            <tr>
              <th scope="row"></th>
              <td></td>
              <td></td>
              <td></td>
              <td>{{ cart.get_total_price() }}</td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2 mx-auto">
        <a href="{{ url_for('cart.finish', cart_id=cart.id) }}" class="btn btn-primary d-block">
          Make Order
        </a>
      </div>
    </div>
  </div>
{% endblock %}

templates/users/order_details.html
{% extends "base.html" %}

{% block content %}
  <div class="container my-4">
    <div class="row">
      <div class="col-4">
        <h1>Order #{{ order.id }}</h1>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-12">
        <table class="table table-striped">
          <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Amount</th>
            <th scope="col">Total Price</th>
          </tr>
          </thead>
          <tbody>
          {% for item in cart_items %}
            <tr>
              <th scope="row">{{ item.id }}</th>
              <td>{{ item.product.name }}</td>
              <td>{{ item.product.price }}</td>
              <td>{{ item.amount }}</td>
              <td>{{ item.get_total_price() }}</td>
            </tr>
          {% endfor %}
          <tr>
            <th scope="row"></th>
            <td></td>
            <td></td>
            <td></td>
            <td>{{ order.cart.get_total_price() }}</td>
            <td></td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

templates/users/orders.html
{% extends "base.html" %}

{% block content %}
  <div class="container my-4">
    <div class="row">
      <div class="col-4">
        <h1>Orders</h1>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-12">
        <table class="table table-striped">
          <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Total Price</th>
            <th scope="col">Address</th>
            <th scope="col"></th>
          </tr>
          </thead>
          <tbody>
          {% for order in orders %}
            <tr>
              <th scope="row">{{ order.id }}</th>
              <td>{{ order.total }} EUR</td>
              <td>{{ order.address }}</td>
              <td>
                <a href="{{ url_for('user.order_details', user_id=session.user_id, order_id=order.id) }}" type="button" class="btn btn-outline-primary">View</a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}